# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-ShowStatus
version:      0.01
version_from: lib/Apache/ShowStatus.pm
installdirs:  site
requires:
    Apache::Test:                  
    Sys::Proctitle:                0.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
